import { RequestHandler, Router } from "express";
import { PropertyController } from "@/interfaces/http/controllers/PropertyController";
import { asyncHandler } from "@/interfaces/http/asyncHandler";
import { validate } from "@/interfaces/http/middleware/validate";
import { authorize } from "@/interfaces/http/middleware/authorize";
import { uploadPropertyImages } from "@/interfaces/http/middleware/imageUpload";
import { cacheControl } from "@/interfaces/http/middleware/cacheControl";
import {
  createPropertySchema,
  updatePropertySchema,
  searchPropertiesQuerySchema,
  reportPropertySchema,
  paginationQuerySchema,
  propertyIdParamSchema,
  propertyImageParamSchema,
  recommendationsQuerySchema,
  postalCodeLookupQuerySchema,
  reverseGeocodeQuerySchema,
} from "@/interfaces/http/validators/property.schemas";

export function createPropertyRouter(
  controller: PropertyController,
  authenticate: RequestHandler,
  optionalAuthenticate: RequestHandler,
): Router {
  const router = Router();

  // Specific paths BEFORE the /:id catch-all, or "mine"/"favorites" would
  // be parsed as a property id.
  router.get(
    "/mine",
    authenticate,
    validate(paginationQuerySchema, "query"),
    asyncHandler(controller.mine),
  );
  // Phase 3 Part 3 (Owner Dashboard, must-have slice). No query params, so
  // no validate() call -- kept next to "/mine" for the same route-ordering
  // reason as the rest of this block (must come before "/:id").
  router.get("/mine/stats", authenticate, asyncHandler(controller.myStats));
  router.get(
    "/favorites",
    authenticate,
    validate(paginationQuerySchema, "query"),
    asyncHandler(controller.favorites),
  );
  // Not one of Phase 3's 12 listed endpoints, but necessary supporting
  // plumbing: the frontend needs real category IDs (generated by the seed
  // migration) to populate the Add/Edit Property forms and the Search
  // page's Category filter. Registered before "/:id" for the same
  // route-ordering reason as "/mine" and "/favorites" above.
  // Phase 6 Part 3 (performance): this list is effectively static --
  // safe to let a CDN/browser cache it for a few minutes.
  router.get("/categories", cacheControl(300), asyncHandler(controller.categories));

  // Homepage "Platform Statistics" redesign: real aggregate counts only
  // (active listings, categories, cities covered, verified owners), no
  // invented figures. Public/no-auth, same route-ordering reason as
  // "/mine", "/favorites", "/categories" above -- must come before
  // "/:id". Short cache is safe: these are slow-moving aggregates, not
  // per-request-sensitive data.
  router.get("/stats", cacheControl(300), asyncHandler(controller.stats));

  // Phase 5 Parts 6-7 (Recently Viewed / Recommendations) -- same
  // route-ordering reason as /mine, /favorites, /categories above.
  router.get("/recently-viewed", authenticate, asyncHandler(controller.recentlyViewed));
  router.get(
    "/recommendations",
    authenticate,
    validate(recommendationsQuerySchema, "query"),
    asyncHandler(controller.recommendationsForMe),
  );

  // Phase 2 Part 1 (PIN-first Address step): must come before "/:id" for the
  // same route-ordering reason as "/mine"/"/favorites"/"/categories" above --
  // "/geocode/postal-code" and "/geocode/reverse" are two-segment paths so
  // they'd never actually collide with the one-segment "/:id" pattern, but
  // keeping them grouped with the other pre-"/:id" routes avoids relying on
  // that being obvious later.
  router.get(
    "/geocode/postal-code",
    validate(postalCodeLookupQuerySchema, "query"),
    asyncHandler(controller.geocodePostalCodeLookup),
  );
  router.get(
    "/geocode/reverse",
    validate(reverseGeocodeQuerySchema, "query"),
    asyncHandler(controller.reverseGeocodeLocationLookup),
  );

  router.get("/", validate(searchPropertiesQuerySchema, "query"), asyncHandler(controller.search));

  router.post(
    "/",
    authenticate,
    authorize("property_owner", "admin", "super_admin"),
    validate(createPropertySchema),
    asyncHandler(controller.create),
  );

  router.get(
    "/:id",
    optionalAuthenticate,
    validate(propertyIdParamSchema, "params"),
    asyncHandler(controller.getById),
  );

  router.patch(
    "/:id",
    authenticate,
    validate(propertyIdParamSchema, "params"),
    validate(updatePropertySchema),
    asyncHandler(controller.update),
  );

  router.delete(
    "/:id",
    authenticate,
    validate(propertyIdParamSchema, "params"),
    asyncHandler(controller.remove),
  );

  router.post(
    "/:id/images",
    authenticate,
    validate(propertyIdParamSchema, "params"),
    uploadPropertyImages(),
    asyncHandler(controller.uploadImages),
  );

  router.delete(
    "/:id/images/:imageId",
    authenticate,
    validate(propertyImageParamSchema, "params"),
    asyncHandler(controller.deleteImage),
  );

  router.post(
    "/:id/favorite",
    authenticate,
    validate(propertyIdParamSchema, "params"),
    asyncHandler(controller.favorite),
  );

  router.delete(
    "/:id/favorite",
    authenticate,
    validate(propertyIdParamSchema, "params"),
    asyncHandler(controller.unfavorite),
  );

  router.post(
    "/:id/report",
    authenticate,
    validate(propertyIdParamSchema, "params"),
    validate(reportPropertySchema),
    asyncHandler(controller.report),
  );

  router.get(
    "/:id/recommendations",
    optionalAuthenticate,
    validate(propertyIdParamSchema, "params"),
    validate(recommendationsQuerySchema, "query"),
    asyncHandler(controller.recommendationsForProperty),
  );

  return router;
}
